# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/styles/Code/Research_S16

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/styles/Code/Research_S16

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/styles/Code/Research_S16/CMakeFiles /Users/styles/Code/Research_S16/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/styles/Code/Research_S16/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ResearchDNNGenerator

# Build rule for target.
ResearchDNNGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ResearchDNNGenerator
.PHONY : ResearchDNNGenerator

# fast build rule for target.
ResearchDNNGenerator/fast:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/build
.PHONY : ResearchDNNGenerator/fast

ece8270project/Channel.o: ece8270project/Channel.cpp.o

.PHONY : ece8270project/Channel.o

# target to build an object file
ece8270project/Channel.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/ece8270project/Channel.cpp.o
.PHONY : ece8270project/Channel.cpp.o

ece8270project/Channel.i: ece8270project/Channel.cpp.i

.PHONY : ece8270project/Channel.i

# target to preprocess a source file
ece8270project/Channel.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/ece8270project/Channel.cpp.i
.PHONY : ece8270project/Channel.cpp.i

ece8270project/Channel.s: ece8270project/Channel.cpp.s

.PHONY : ece8270project/Channel.s

# target to generate assembly for a file
ece8270project/Channel.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/ece8270project/Channel.cpp.s
.PHONY : ece8270project/Channel.cpp.s

ece8270project/Image.o: ece8270project/Image.cpp.o

.PHONY : ece8270project/Image.o

# target to build an object file
ece8270project/Image.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/ece8270project/Image.cpp.o
.PHONY : ece8270project/Image.cpp.o

ece8270project/Image.i: ece8270project/Image.cpp.i

.PHONY : ece8270project/Image.i

# target to preprocess a source file
ece8270project/Image.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/ece8270project/Image.cpp.i
.PHONY : ece8270project/Image.cpp.i

ece8270project/Image.s: ece8270project/Image.cpp.s

.PHONY : ece8270project/Image.s

# target to generate assembly for a file
ece8270project/Image.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/ece8270project/Image.cpp.s
.PHONY : ece8270project/Image.cpp.s

layers/ConvolutionLayer.o: layers/ConvolutionLayer.cpp.o

.PHONY : layers/ConvolutionLayer.o

# target to build an object file
layers/ConvolutionLayer.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/ConvolutionLayer.cpp.o
.PHONY : layers/ConvolutionLayer.cpp.o

layers/ConvolutionLayer.i: layers/ConvolutionLayer.cpp.i

.PHONY : layers/ConvolutionLayer.i

# target to preprocess a source file
layers/ConvolutionLayer.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/ConvolutionLayer.cpp.i
.PHONY : layers/ConvolutionLayer.cpp.i

layers/ConvolutionLayer.s: layers/ConvolutionLayer.cpp.s

.PHONY : layers/ConvolutionLayer.s

# target to generate assembly for a file
layers/ConvolutionLayer.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/ConvolutionLayer.cpp.s
.PHONY : layers/ConvolutionLayer.cpp.s

layers/InnerProductLayer.o: layers/InnerProductLayer.cpp.o

.PHONY : layers/InnerProductLayer.o

# target to build an object file
layers/InnerProductLayer.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/InnerProductLayer.cpp.o
.PHONY : layers/InnerProductLayer.cpp.o

layers/InnerProductLayer.i: layers/InnerProductLayer.cpp.i

.PHONY : layers/InnerProductLayer.i

# target to preprocess a source file
layers/InnerProductLayer.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/InnerProductLayer.cpp.i
.PHONY : layers/InnerProductLayer.cpp.i

layers/InnerProductLayer.s: layers/InnerProductLayer.cpp.s

.PHONY : layers/InnerProductLayer.s

# target to generate assembly for a file
layers/InnerProductLayer.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/InnerProductLayer.cpp.s
.PHONY : layers/InnerProductLayer.cpp.s

layers/InputLayer.o: layers/InputLayer.cpp.o

.PHONY : layers/InputLayer.o

# target to build an object file
layers/InputLayer.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/InputLayer.cpp.o
.PHONY : layers/InputLayer.cpp.o

layers/InputLayer.i: layers/InputLayer.cpp.i

.PHONY : layers/InputLayer.i

# target to preprocess a source file
layers/InputLayer.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/InputLayer.cpp.i
.PHONY : layers/InputLayer.cpp.i

layers/InputLayer.s: layers/InputLayer.cpp.s

.PHONY : layers/InputLayer.s

# target to generate assembly for a file
layers/InputLayer.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/InputLayer.cpp.s
.PHONY : layers/InputLayer.cpp.s

layers/LRNLayer.o: layers/LRNLayer.cpp.o

.PHONY : layers/LRNLayer.o

# target to build an object file
layers/LRNLayer.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/LRNLayer.cpp.o
.PHONY : layers/LRNLayer.cpp.o

layers/LRNLayer.i: layers/LRNLayer.cpp.i

.PHONY : layers/LRNLayer.i

# target to preprocess a source file
layers/LRNLayer.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/LRNLayer.cpp.i
.PHONY : layers/LRNLayer.cpp.i

layers/LRNLayer.s: layers/LRNLayer.cpp.s

.PHONY : layers/LRNLayer.s

# target to generate assembly for a file
layers/LRNLayer.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/LRNLayer.cpp.s
.PHONY : layers/LRNLayer.cpp.s

layers/LayerBase.o: layers/LayerBase.cpp.o

.PHONY : layers/LayerBase.o

# target to build an object file
layers/LayerBase.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/LayerBase.cpp.o
.PHONY : layers/LayerBase.cpp.o

layers/LayerBase.i: layers/LayerBase.cpp.i

.PHONY : layers/LayerBase.i

# target to preprocess a source file
layers/LayerBase.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/LayerBase.cpp.i
.PHONY : layers/LayerBase.cpp.i

layers/LayerBase.s: layers/LayerBase.cpp.s

.PHONY : layers/LayerBase.s

# target to generate assembly for a file
layers/LayerBase.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/LayerBase.cpp.s
.PHONY : layers/LayerBase.cpp.s

layers/PoolingLayer.o: layers/PoolingLayer.cpp.o

.PHONY : layers/PoolingLayer.o

# target to build an object file
layers/PoolingLayer.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/PoolingLayer.cpp.o
.PHONY : layers/PoolingLayer.cpp.o

layers/PoolingLayer.i: layers/PoolingLayer.cpp.i

.PHONY : layers/PoolingLayer.i

# target to preprocess a source file
layers/PoolingLayer.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/PoolingLayer.cpp.i
.PHONY : layers/PoolingLayer.cpp.i

layers/PoolingLayer.s: layers/PoolingLayer.cpp.s

.PHONY : layers/PoolingLayer.s

# target to generate assembly for a file
layers/PoolingLayer.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/PoolingLayer.cpp.s
.PHONY : layers/PoolingLayer.cpp.s

layers/ReLULayer.o: layers/ReLULayer.cpp.o

.PHONY : layers/ReLULayer.o

# target to build an object file
layers/ReLULayer.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/ReLULayer.cpp.o
.PHONY : layers/ReLULayer.cpp.o

layers/ReLULayer.i: layers/ReLULayer.cpp.i

.PHONY : layers/ReLULayer.i

# target to preprocess a source file
layers/ReLULayer.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/ReLULayer.cpp.i
.PHONY : layers/ReLULayer.cpp.i

layers/ReLULayer.s: layers/ReLULayer.cpp.s

.PHONY : layers/ReLULayer.s

# target to generate assembly for a file
layers/ReLULayer.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/ReLULayer.cpp.s
.PHONY : layers/ReLULayer.cpp.s

layers/SoftmaxLayer.o: layers/SoftmaxLayer.cpp.o

.PHONY : layers/SoftmaxLayer.o

# target to build an object file
layers/SoftmaxLayer.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/SoftmaxLayer.cpp.o
.PHONY : layers/SoftmaxLayer.cpp.o

layers/SoftmaxLayer.i: layers/SoftmaxLayer.cpp.i

.PHONY : layers/SoftmaxLayer.i

# target to preprocess a source file
layers/SoftmaxLayer.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/SoftmaxLayer.cpp.i
.PHONY : layers/SoftmaxLayer.cpp.i

layers/SoftmaxLayer.s: layers/SoftmaxLayer.cpp.s

.PHONY : layers/SoftmaxLayer.s

# target to generate assembly for a file
layers/SoftmaxLayer.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/SoftmaxLayer.cpp.s
.PHONY : layers/SoftmaxLayer.cpp.s

layers/layer_helpers/LayerTypes.o: layers/layer_helpers/LayerTypes.cpp.o

.PHONY : layers/layer_helpers/LayerTypes.o

# target to build an object file
layers/layer_helpers/LayerTypes.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/layer_helpers/LayerTypes.cpp.o
.PHONY : layers/layer_helpers/LayerTypes.cpp.o

layers/layer_helpers/LayerTypes.i: layers/layer_helpers/LayerTypes.cpp.i

.PHONY : layers/layer_helpers/LayerTypes.i

# target to preprocess a source file
layers/layer_helpers/LayerTypes.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/layer_helpers/LayerTypes.cpp.i
.PHONY : layers/layer_helpers/LayerTypes.cpp.i

layers/layer_helpers/LayerTypes.s: layers/layer_helpers/LayerTypes.cpp.s

.PHONY : layers/layer_helpers/LayerTypes.s

# target to generate assembly for a file
layers/layer_helpers/LayerTypes.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/layer_helpers/LayerTypes.cpp.s
.PHONY : layers/layer_helpers/LayerTypes.cpp.s

layers/layer_helpers/Param.o: layers/layer_helpers/Param.cpp.o

.PHONY : layers/layer_helpers/Param.o

# target to build an object file
layers/layer_helpers/Param.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/layer_helpers/Param.cpp.o
.PHONY : layers/layer_helpers/Param.cpp.o

layers/layer_helpers/Param.i: layers/layer_helpers/Param.cpp.i

.PHONY : layers/layer_helpers/Param.i

# target to preprocess a source file
layers/layer_helpers/Param.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/layer_helpers/Param.cpp.i
.PHONY : layers/layer_helpers/Param.cpp.i

layers/layer_helpers/Param.s: layers/layer_helpers/Param.cpp.s

.PHONY : layers/layer_helpers/Param.s

# target to generate assembly for a file
layers/layer_helpers/Param.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/layers/layer_helpers/Param.cpp.s
.PHONY : layers/layer_helpers/Param.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/main.cpp.s
.PHONY : main.cpp.s

prototxt/Prototxt.o: prototxt/Prototxt.cpp.o

.PHONY : prototxt/Prototxt.o

# target to build an object file
prototxt/Prototxt.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/prototxt/Prototxt.cpp.o
.PHONY : prototxt/Prototxt.cpp.o

prototxt/Prototxt.i: prototxt/Prototxt.cpp.i

.PHONY : prototxt/Prototxt.i

# target to preprocess a source file
prototxt/Prototxt.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/prototxt/Prototxt.cpp.i
.PHONY : prototxt/Prototxt.cpp.i

prototxt/Prototxt.s: prototxt/Prototxt.cpp.s

.PHONY : prototxt/Prototxt.s

# target to generate assembly for a file
prototxt/Prototxt.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/prototxt/Prototxt.cpp.s
.PHONY : prototxt/Prototxt.cpp.s

solvers/SGDSolver.o: solvers/SGDSolver.cpp.o

.PHONY : solvers/SGDSolver.o

# target to build an object file
solvers/SGDSolver.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/SGDSolver.cpp.o
.PHONY : solvers/SGDSolver.cpp.o

solvers/SGDSolver.i: solvers/SGDSolver.cpp.i

.PHONY : solvers/SGDSolver.i

# target to preprocess a source file
solvers/SGDSolver.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/SGDSolver.cpp.i
.PHONY : solvers/SGDSolver.cpp.i

solvers/SGDSolver.s: solvers/SGDSolver.cpp.s

.PHONY : solvers/SGDSolver.s

# target to generate assembly for a file
solvers/SGDSolver.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/SGDSolver.cpp.s
.PHONY : solvers/SGDSolver.cpp.s

solvers/SolverBase.o: solvers/SolverBase.cpp.o

.PHONY : solvers/SolverBase.o

# target to build an object file
solvers/SolverBase.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/SolverBase.cpp.o
.PHONY : solvers/SolverBase.cpp.o

solvers/SolverBase.i: solvers/SolverBase.cpp.i

.PHONY : solvers/SolverBase.i

# target to preprocess a source file
solvers/SolverBase.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/SolverBase.cpp.i
.PHONY : solvers/SolverBase.cpp.i

solvers/SolverBase.s: solvers/SolverBase.cpp.s

.PHONY : solvers/SolverBase.s

# target to generate assembly for a file
solvers/SolverBase.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/SolverBase.cpp.s
.PHONY : solvers/SolverBase.cpp.s

solvers/solver_helpers/Snapshot.o: solvers/solver_helpers/Snapshot.cpp.o

.PHONY : solvers/solver_helpers/Snapshot.o

# target to build an object file
solvers/solver_helpers/Snapshot.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/solver_helpers/Snapshot.cpp.o
.PHONY : solvers/solver_helpers/Snapshot.cpp.o

solvers/solver_helpers/Snapshot.i: solvers/solver_helpers/Snapshot.cpp.i

.PHONY : solvers/solver_helpers/Snapshot.i

# target to preprocess a source file
solvers/solver_helpers/Snapshot.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/solver_helpers/Snapshot.cpp.i
.PHONY : solvers/solver_helpers/Snapshot.cpp.i

solvers/solver_helpers/Snapshot.s: solvers/solver_helpers/Snapshot.cpp.s

.PHONY : solvers/solver_helpers/Snapshot.s

# target to generate assembly for a file
solvers/solver_helpers/Snapshot.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/solvers/solver_helpers/Snapshot.cpp.s
.PHONY : solvers/solver_helpers/Snapshot.cpp.s

utils/GenerateLayers.o: utils/GenerateLayers.cpp.o

.PHONY : utils/GenerateLayers.o

# target to build an object file
utils/GenerateLayers.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/utils/GenerateLayers.cpp.o
.PHONY : utils/GenerateLayers.cpp.o

utils/GenerateLayers.i: utils/GenerateLayers.cpp.i

.PHONY : utils/GenerateLayers.i

# target to preprocess a source file
utils/GenerateLayers.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/utils/GenerateLayers.cpp.i
.PHONY : utils/GenerateLayers.cpp.i

utils/GenerateLayers.s: utils/GenerateLayers.cpp.s

.PHONY : utils/GenerateLayers.s

# target to generate assembly for a file
utils/GenerateLayers.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/utils/GenerateLayers.cpp.s
.PHONY : utils/GenerateLayers.cpp.s

utils/UserInput.o: utils/UserInput.cpp.o

.PHONY : utils/UserInput.o

# target to build an object file
utils/UserInput.cpp.o:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/utils/UserInput.cpp.o
.PHONY : utils/UserInput.cpp.o

utils/UserInput.i: utils/UserInput.cpp.i

.PHONY : utils/UserInput.i

# target to preprocess a source file
utils/UserInput.cpp.i:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/utils/UserInput.cpp.i
.PHONY : utils/UserInput.cpp.i

utils/UserInput.s: utils/UserInput.cpp.s

.PHONY : utils/UserInput.s

# target to generate assembly for a file
utils/UserInput.cpp.s:
	$(MAKE) -f CMakeFiles/ResearchDNNGenerator.dir/build.make CMakeFiles/ResearchDNNGenerator.dir/utils/UserInput.cpp.s
.PHONY : utils/UserInput.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ResearchDNNGenerator"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ece8270project/Channel.o"
	@echo "... ece8270project/Channel.i"
	@echo "... ece8270project/Channel.s"
	@echo "... ece8270project/Image.o"
	@echo "... ece8270project/Image.i"
	@echo "... ece8270project/Image.s"
	@echo "... layers/ConvolutionLayer.o"
	@echo "... layers/ConvolutionLayer.i"
	@echo "... layers/ConvolutionLayer.s"
	@echo "... layers/InnerProductLayer.o"
	@echo "... layers/InnerProductLayer.i"
	@echo "... layers/InnerProductLayer.s"
	@echo "... layers/InputLayer.o"
	@echo "... layers/InputLayer.i"
	@echo "... layers/InputLayer.s"
	@echo "... layers/LRNLayer.o"
	@echo "... layers/LRNLayer.i"
	@echo "... layers/LRNLayer.s"
	@echo "... layers/LayerBase.o"
	@echo "... layers/LayerBase.i"
	@echo "... layers/LayerBase.s"
	@echo "... layers/PoolingLayer.o"
	@echo "... layers/PoolingLayer.i"
	@echo "... layers/PoolingLayer.s"
	@echo "... layers/ReLULayer.o"
	@echo "... layers/ReLULayer.i"
	@echo "... layers/ReLULayer.s"
	@echo "... layers/SoftmaxLayer.o"
	@echo "... layers/SoftmaxLayer.i"
	@echo "... layers/SoftmaxLayer.s"
	@echo "... layers/layer_helpers/LayerTypes.o"
	@echo "... layers/layer_helpers/LayerTypes.i"
	@echo "... layers/layer_helpers/LayerTypes.s"
	@echo "... layers/layer_helpers/Param.o"
	@echo "... layers/layer_helpers/Param.i"
	@echo "... layers/layer_helpers/Param.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... prototxt/Prototxt.o"
	@echo "... prototxt/Prototxt.i"
	@echo "... prototxt/Prototxt.s"
	@echo "... solvers/SGDSolver.o"
	@echo "... solvers/SGDSolver.i"
	@echo "... solvers/SGDSolver.s"
	@echo "... solvers/SolverBase.o"
	@echo "... solvers/SolverBase.i"
	@echo "... solvers/SolverBase.s"
	@echo "... solvers/solver_helpers/Snapshot.o"
	@echo "... solvers/solver_helpers/Snapshot.i"
	@echo "... solvers/solver_helpers/Snapshot.s"
	@echo "... utils/GenerateLayers.o"
	@echo "... utils/GenerateLayers.i"
	@echo "... utils/GenerateLayers.s"
	@echo "... utils/UserInput.o"
	@echo "... utils/UserInput.i"
	@echo "... utils/UserInput.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

